"""Final Fix with Use Alter

Revision ID: 82877110cf80
Revises: 
Create Date: 2025-12-15 09:08:04.640768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82877110cf80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BienLai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_bien_lai', sa.String(length=50), nullable=False),
    sa.Column('ngay_thanh_toan', sa.DateTime(), nullable=True),
    sa.Column('ho_khau_info', sa.Unicode(length=255), nullable=True),
    sa.Column('nguoi_thanh_toan', sa.Unicode(length=100), nullable=True),
    sa.Column('tong_tien', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('chi_tiet', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_bien_lai')
    )
    op.create_table('Ho_khau',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_so_ho_khau', sa.String(length=50), nullable=False),
    sa.Column('chu_ho_id', sa.Integer(), nullable=True),
    sa.Column('so_nha', sa.Unicode(length=50), nullable=False),
    sa.Column('duong_pho', sa.Unicode(length=100), nullable=False),
    sa.Column('phuong_xa', sa.Unicode(length=100), nullable=False),
    sa.Column('quan_huyen', sa.Unicode(length=100), nullable=False),
    sa.Column('ngay_tao', sa.Date(), nullable=True),
    sa.Column('ghi_chu', sa.UnicodeText(), nullable=True),
    sa.Column('so_dien', sa.Integer(), nullable=True),
    sa.Column('so_nuoc', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chu_ho_id'], ['Nhan_khau.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_so_ho_khau')
    )
    op.create_table('LoaiPhi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten_phi', sa.Unicode(length=100), nullable=False),
    sa.Column('don_gia', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('don_vi', sa.Unicode(length=20), nullable=True),
    sa.Column('bat_buoc', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Nhan_khau',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ho_ten', sa.Unicode(length=100), nullable=False),
    sa.Column('bi_danh', sa.Unicode(length=50), nullable=True),
    sa.Column('ngay_sinh', sa.Date(), nullable=False),
    sa.Column('gioi_tinh', sa.Unicode(length=10), nullable=False),
    sa.Column('nguyen_quan', sa.Unicode(length=255), nullable=True),
    sa.Column('dan_toc', sa.Unicode(length=50), nullable=True),
    sa.Column('nghe_nghiep', sa.Unicode(length=100), nullable=True),
    sa.Column('noi_lam_viec', sa.Unicode(length=100), nullable=True),
    sa.Column('so_cccd', sa.String(length=12), nullable=True),
    sa.Column('ngay_cap', sa.Date(), nullable=True),
    sa.Column('noi_cap', sa.Unicode(length=100), nullable=True),
    sa.Column('id_ho_khau', sa.Integer(), nullable=True),
    sa.Column('ngay_dang_ky_thuong_tru', sa.Date(), nullable=True),
    sa.Column('noi_thuong_tru', sa.Unicode(length=255), nullable=True),
    sa.Column('tinh_trang', sa.Unicode(length=20), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_ho_khau'], ['Ho_khau.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Nhan_khau', schema=None) as batch_op:
        batch_op.create_index('idx_so_cccd_unique', ['so_cccd'], unique=True, mssql_where=sa.text('so_cccd IS NOT NULL'))

    op.create_table('ChiSoDienNuoc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ho_khau_id', sa.Integer(), nullable=False),
    sa.Column('thang', sa.String(length=7), nullable=False),
    sa.Column('chi_so_dien_cu', sa.Integer(), nullable=True),
    sa.Column('chi_so_dien_moi', sa.Integer(), nullable=False),
    sa.Column('chi_so_nuoc_cu', sa.Integer(), nullable=True),
    sa.Column('chi_so_nuoc_moi', sa.Integer(), nullable=False),
    sa.Column('ngay_ghi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ho_khau_id'], ['Ho_khau.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LichSuHoKhau',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ho_khau_id', sa.Integer(), nullable=True),
    sa.Column('noi_dung', sa.UnicodeText(), nullable=False),
    sa.Column('ngay_thuc_hien', sa.DateTime(), nullable=True),
    sa.Column('nguoi_thuc_hien', sa.Unicode(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ho_khau_id'], ['Ho_khau.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nhan_khau_ho_khau',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ho_khau_id', sa.Integer(), nullable=False),
    sa.Column('nhan_khau_id', sa.Integer(), nullable=False),
    sa.Column('quan_he_chu_ho', sa.Unicode(length=50), nullable=False),
    sa.Column('ngay_bat_dau', sa.Date(), nullable=True),
    sa.Column('ngay_ket_thuc', sa.Date(), nullable=True),
    sa.Column('trang_thai', sa.Unicode(length=100), nullable=True),
    sa.Column('ghi_chu', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['ho_khau_id'], ['Ho_khau.id'], ),
    sa.ForeignKeyConstraint(['nhan_khau_id'], ['Nhan_khau.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tai_khoan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('ho_ten', sa.Unicode(length=100), nullable=True),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('nhan_khau_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nhan_khau_id'], ['Nhan_khau.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tam_tru',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('noi_tam_tru', sa.Unicode(length=255), nullable=False),
    sa.Column('ngay_bat_dau', sa.Date(), nullable=False),
    sa.Column('ngay_ket_thuc', sa.Date(), nullable=False),
    sa.Column('ly_do', sa.UnicodeText(), nullable=True),
    sa.Column('status', sa.Unicode(length=20), nullable=True),
    sa.ForeignKeyConstraint(['resident_id'], ['Nhan_khau.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tam_vang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('noi_den', sa.Unicode(length=255), nullable=False),
    sa.Column('ngay_bat_dau', sa.Date(), nullable=False),
    sa.Column('ngay_ket_thuc', sa.Date(), nullable=True),
    sa.Column('ly_do', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['resident_id'], ['Nhan_khau.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thong_bao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nguoi_nhan_id', sa.Integer(), nullable=False),
    sa.Column('noi_dung', sa.UnicodeText(), nullable=False),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('da_doc', sa.Boolean(), nullable=True),
    sa.Column('loai_thong_bao', sa.Unicode(length=20), nullable=True),
    sa.Column('loai_phi_id', sa.Integer(), nullable=True),
    sa.Column('so_tien', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('hinh_thuc_thu', sa.Unicode(length=20), nullable=True),
    sa.ForeignKeyConstraint(['loai_phi_id'], ['LoaiPhi.id'], ),
    sa.ForeignKeyConstraint(['nguoi_nhan_id'], ['tai_khoan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yeu_cau',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nguoi_gui_id', sa.Integer(), nullable=False),
    sa.Column('loai_yeu_cau', sa.Unicode(length=50), nullable=False),
    sa.Column('noi_dung', sa.UnicodeText(), nullable=False),
    sa.Column('ngay_gui', sa.DateTime(), nullable=True),
    sa.Column('trang_thai', sa.Unicode(length=50), nullable=True),
    sa.Column('phan_hoi', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['nguoi_gui_id'], ['tai_khoan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Giao_dich',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nhan_khau_id', sa.Integer(), nullable=False),
    sa.Column('ho_khau_id', sa.Integer(), nullable=True),
    sa.Column('loai_phi_id', sa.Integer(), nullable=False),
    sa.Column('so_luong_tieu_thu', sa.Integer(), nullable=True),
    sa.Column('don_gia_ap_dung', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('so_tien', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('phuong_thuc', sa.Unicode(length=50), nullable=False),
    sa.Column('ngay_nop', sa.DateTime(), nullable=True),
    sa.Column('trang_thai', sa.Unicode(length=50), nullable=True),
    sa.Column('thong_bao_id', sa.Integer(), nullable=True),
    sa.Column('bien_lai_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bien_lai_id'], ['BienLai.id'], ),
    sa.ForeignKeyConstraint(['ho_khau_id'], ['Ho_khau.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loai_phi_id'], ['LoaiPhi.id'], ),
    sa.ForeignKeyConstraint(['nhan_khau_id'], ['Nhan_khau.id'], ),
    sa.ForeignKeyConstraint(['thong_bao_id'], ['thong_bao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ThuChi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ho_khau_id', sa.Integer(), nullable=True),
    sa.Column('loai_giao_dich', sa.Unicode(length=10), nullable=False),
    sa.Column('so_tien', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('hinh_thuc', sa.Unicode(length=50), nullable=True),
    sa.Column('ngay_giao_dich', sa.DateTime(), nullable=True),
    sa.Column('giao_dich_id', sa.Integer(), nullable=True),
    sa.Column('ghi_chu', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['giao_dich_id'], ['Giao_dich.id'], ),
    sa.ForeignKeyConstraint(['ho_khau_id'], ['Ho_khau.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ThuChi')
    op.drop_table('Giao_dich')
    op.drop_table('yeu_cau')
    op.drop_table('thong_bao')
    op.drop_table('tam_vang')
    op.drop_table('tam_tru')
    op.drop_table('tai_khoan')
    op.drop_table('nhan_khau_ho_khau')
    op.drop_table('LichSuHoKhau')
    op.drop_table('ChiSoDienNuoc')
    with op.batch_alter_table('Nhan_khau', schema=None) as batch_op:
        batch_op.drop_index('idx_so_cccd_unique', mssql_where=sa.text('so_cccd IS NOT NULL'))

    op.drop_table('Nhan_khau')
    op.drop_table('LoaiPhi')
    op.drop_table('Ho_khau')
    op.drop_table('BienLai')
    # ### end Alembic commands ###
