"""Add BienLai, YeuCau, LichSu tables

Revision ID: e646faa5a815
Revises: 41ce93f46811
Create Date: 2025-11-17 12:38:10.735157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e646faa5a815'
down_revision = '41ce93f46811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BienLai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_bien_lai', sa.String(length=50), nullable=False),
    sa.Column('ngay_thanh_toan', sa.DateTime(), nullable=True),
    sa.Column('ho_khau_info', sa.Unicode(length=255), nullable=True),
    sa.Column('nguoi_thanh_toan', sa.Unicode(length=100), nullable=True),
    sa.Column('tong_tien', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('chi_tiet', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_bien_lai')
    )
    op.create_table('ChiSoDienNuoc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ho_khau_id', sa.Integer(), nullable=False),
    sa.Column('thang', sa.String(length=7), nullable=False),
    sa.Column('chi_so_dien_cu', sa.Integer(), nullable=True),
    sa.Column('chi_so_dien_moi', sa.Integer(), nullable=False),
    sa.Column('chi_so_nuoc_cu', sa.Integer(), nullable=True),
    sa.Column('chi_so_nuoc_moi', sa.Integer(), nullable=False),
    sa.Column('ngay_ghi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ho_khau_id'], ['Ho_khau.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LichSuHoKhau',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ho_khau_id', sa.Integer(), nullable=True),
    sa.Column('noi_dung', sa.UnicodeText(), nullable=False),
    sa.Column('ngay_thuc_hien', sa.DateTime(), nullable=True),
    sa.Column('nguoi_thuc_hien', sa.Unicode(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ho_khau_id'], ['Ho_khau.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Giao_dich', schema=None) as batch_op:
        batch_op.add_column(sa.Column('so_luong_tieu_thu', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('don_gia_ap_dung', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('thong_bao_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bien_lai_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'BienLai', ['bien_lai_id'], ['id'])
        batch_op.create_foreign_key(None, 'thong_bao', ['thong_bao_id'], ['id'])

    with op.batch_alter_table('Ho_khau', schema=None) as batch_op:
        batch_op.alter_column('ma_so_ho_khau',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('LoaiPhi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('don_gia', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('don_vi', sa.Unicode(length=20), nullable=True))

    with op.batch_alter_table('Nhan_khau', schema=None) as batch_op:
        batch_op.alter_column('gioi_tinh',
               existing_type=sa.NVARCHAR(length=3, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=10),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_nhan_khau_ho_khau'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Ho_khau', ['id_ho_khau'], ['id'])

    with op.batch_alter_table('tam_tru', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Unicode(length=20), nullable=True))
        batch_op.alter_column('ngay_ket_thuc',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('yeu_cau', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loai_yeu_cau', sa.Unicode(length=50), nullable=False))
        batch_op.add_column(sa.Column('phan_hoi', sa.UnicodeText(), nullable=True))
        batch_op.alter_column('trang_thai',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yeu_cau', schema=None) as batch_op:
        batch_op.alter_column('trang_thai',
               existing_type=sa.Unicode(length=50),
               type_=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.drop_column('phan_hoi')
        batch_op.drop_column('loai_yeu_cau')

    with op.batch_alter_table('tam_tru', schema=None) as batch_op:
        batch_op.alter_column('ngay_ket_thuc',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('status')

    with op.batch_alter_table('Nhan_khau', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_nhan_khau_ho_khau'), 'Ho_khau', ['id_ho_khau'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('gioi_tinh',
               existing_type=sa.Unicode(length=10),
               type_=sa.NVARCHAR(length=3, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('LoaiPhi', schema=None) as batch_op:
        batch_op.drop_column('don_vi')
        batch_op.drop_column('don_gia')

    with op.batch_alter_table('Ho_khau', schema=None) as batch_op:
        batch_op.alter_column('ma_so_ho_khau',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('Giao_dich', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bien_lai_id')
        batch_op.drop_column('thong_bao_id')
        batch_op.drop_column('don_gia_ap_dung')
        batch_op.drop_column('so_luong_tieu_thu')

    op.drop_table('LichSuHoKhau')
    op.drop_table('ChiSoDienNuoc')
    op.drop_table('BienLai')
    # ### end Alembic commands ###
